### ISSUE TITLE
--details overview does not work with expanded uris

### ISSUE THREAD

**Issue by ashmanto** [mimiro-io/datahub-cli#136]
`mim query --id "http://data.io/some_set/foo" --details` does not work as expected. it only returns the entity, while not using expandeed uris like so:
`mim query --id "nsX:foo" --details` works as expected.

**Comment by rompetroll** [comment]
https://github.com/mimiro-io/datahub/pull/172 should fix this

**Comment by andebor** [comment]
This is fixed
