### ISSUE TITLE
Datahub and CLI transformations return different values on GetId(*id*) in javascript Transform

### ISSUE THREAD

**Issue by ashmanto** [mimiro-io/datahub-cli#14]
It appears that the CLI returns null instead of an empty object when getId(*id*) does not get a hit.

**Comment by gra-moore** [comment]
Just for clarification, @ashmanto which situation returns null? datahub or cli local?

**Comment by ashmanto** [comment]
Cant remember the details on this, but an example of differences beetween testing and actually running it on the datahub is animal-eanaku.js
I.E ` mim query --id "http://data.mimiro.io/sdb/animal/1" --via="*" --inverse=true --json | mim transform test --file animal-eanaku.js --json |jq .` returns a valid result, while it crashes on the datahub with error `TypeError: Cannot read property 'split' of undefined or null at <eval>:229:53(88)`

**Comment by ashmanto** [comment]
solved with newer version of javascript engine in the datahub.
