### ISSUE TITLE
Add support for mim as a PKI client to data hub or data layer

### ISSUE THREAD

**Issue by gra-moore** [mimiro-io/datahub-cli#89]
With the addition in the data hub and planned support in the data layers for using client certificates the mim should be able to generate a key pair, and then use those when authenticating towards a data hub or data layer. 

mim config --generate-keypair  # to generate a store a local keypair
mim config --client-id <client-id> # set the client id
mim config get-client-profile # returns client id and public key

mim login add --use-client-certificate -server <server> -audience <audience> -alias <local alias>

**Comment by gra-moore** [comment]
The above is already supported in the mim client. But what isnt is that all data layers support getting the JWT token with this flow.

When you say the comms should be done with a certificate what do you mean? At the moment the certificate is used to authenticate and get a JWT token. Are you thinking every request would be signed by a certificate and include a client id?

When I discussed with @rompetroll we kind of landed on not securing access between datahub and layers and instead using the proxy dataset to expose layers that could then be secured and then accessed from the cli.

**Comment by gilgamesjh** [comment]
Leaving the communication with the layers out of this discussion, is this then already implemented, and this issue should be closed?

**Comment by gra-moore** [comment]
Closing as done.
